### ISSUE TITLE
Cloning failes with NullPointerException

### ISSUE THREAD

**Issue by sebastianstucke87** [ViscousPot/GitSync#27] opened 2024-11-17 20:17 UTC
Android 13

`Error: java.lang.NullPointerException: Inflater has been closed`

[Bug Report_ Git Sync - [2024-11-17T20_11_52.056468Z].txt](https://github.com/user-attachments/files/17792280/Bug.Report_.Git.Sync.-.2024-11-17T20_11_52.056468Z.txt)

**Comment by ViscousPot** [comment] 2024-11-18 16:03
This was identified as an issue with the user's repo. Feel free to reopen if I am closing mistakenly :)

**Comment by ViscousPot** [comment] 2024-11-19 20:31
Just coming back to add some further context to this. This turns out to be caused by having files larger than 50MB in your repository. GitSync does not support singular files that large.

**Closed by ViscousPot** 2024-11-19 20:31 UTC
